module.exports = {
  EMOJIS_CUSTOM: {
    'LOADING_EMOJI': '534521618177851393',
    'ONLINE': '488658856709455881',
    'IDLE': '493050914614280192',
    'DND': '488658928540975104',
    'OFFLINE': '488658962535809034',
    'CANCEL': '537327435180408842',
    'SPOTIFY': '560221641922052123'
  },
  EMOJIS: {
    'PING': '🏓',
    'PINGS': '📊',
    'USERS': '👥',
    'QUESTION': '❓',
    'HASH': '#⃣',
    'RAM': '💾',
    'BOOKS': '📚',
    'PC': '💻',
    'WATCH': '⌚',
    'ERROR': '🚫',
    'USAGE': '🖊',
    'ALIASES': '🗝',
    'THUMBS_UP': '👍',
    'THUMBS_DOWN': '👎',
    'CANCEL': '❎',
    'SUCCESS': '✅',
    'MUSIC': '🎵',
    'PAGE': '📄',
    'CROWN': '👑',
    'BOT': '🤖',
    'DEVELOPER': '🛠',
    'ROLES': '📜'
  },
  COLORS: {
    'MESSAGE_DELETE': '36393f',
    'MESSAGE_BULK_DELETE': '36393f',
    'MESSAGE_EDIT': '36393f',
    'MESSAGE_PIN': '36393f',
    'MESSAGE_UNPIN': '36393f',
    'MEMBER_UNBAN': '2ECC71',
    'MEMBER_BAN': 'ff3535'
  },
  LOG_COLORS: {
    'ERROR': 'red',
    'WARN': 'yellow',
    'SUCCESS': 'green',
    'COMMAND_USAGE': 'blue',
    'COLOR_TAG': 'magenta'
  },
  // ASSETS
  SPOTIFY_LOGO_PNG: 'src/assets/spotify-logo.png',
  // URL
  SPOTIFY_LOGO_PNG_URL: 'https://images-na.ssl-images-amazon.com/images/I/51rttY7a%2B9L.png',
  PERMISSIONS: [
    'ADMINISTRATOR',
    'VIEW_AUDIT_LOG',
    'MANAGE_GUILD',
    'MANAGE_ROLES',
    'MANAGE_CHANNELS',
    'KICK_MEMBERS',
    'BAN_MEMBERS',
    'CREATE_INSTANT_INVITE',
    'CHANGE_NICKNAME',
    'MANAGE_NICKNAMES',
    'MANAGE_EMOJIS',
    'MANAGE_WEBHOOKS',
    'VIEW_CHANNEL',
    'SEND_MESSAGES',
    'SEND_TTS_MESSAGES',
    'MANAGE_MESSAGES',
    'EMBED_LINKS',
    'ATTACH_FILES',
    'READ_MESSAGE_HISTORY',
    'MENTION_EVERYONE',
    'USE_EXTERNAL_EMOJIS',
    'ADD_REACTIONS',
    'CONNECT',
    'SPEAK',
    'MUTE_MEMBERS',
    'DEAFEN_MEMBERS',
    'MOVE_MEMBERS',
    'USE_VAD',
    'PRIORITY_SPEAKER'
  ]
}
